selfie2anime/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('to_anime.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_anime/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

to_anime/models.py
from django.contrib import admin
from django.db import models

class Photo(models.Model):
    file = models.ImageField()
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

admin.site.register(Photo)

to_anime/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo

from .to_anime import *

import os

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        filename, file_extension = os.path.splitext(photo.file.path)

        image = Image.open(photo.file)
        # image.save(filename+'-o'+file_extension)

        cropped_image = image.crop((x, y, w+x, h+y))
        cropped_image.save(filename+'-o'+file_extension)
        anime_image = array_to_img(predict(cropped_image), scale=False)
        anime_image.save(photo.file.path)
        return photo

to_anime/views.py
from django.shortcuts import render, redirect

from .models import Photo
from .forms import PhotoForm

import os

def index(request):
	form = PhotoForm()
	photos = None # Photo.objects.all()
	anime = None
	if request.method == 'POST':
		filled_form = PhotoForm(request.POST, request.FILES)
		if filled_form.is_valid():
			photo = filled_form.save()
			print("photo.file.path", photo.file.path)
			anime = Photo.objects.get(file=photo.file.name)
			filename, file_extension = os.path.splitext(photo.file.path)
			return render(request, 'to_anime/photo_list.html', {'form': form, 'original': filename+'-o'+file_extension, 'anime': anime})
	return render(request, 'to_anime/photo_list.html', {'form': form, 'photos': photos})

to_anime/templates/to_anime/index.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Selfie to Anime{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.min.css" integrity="sha512-w+u2vZqMNUVngx+0GVZYM21Qm093kAexjueWOv9e9nIeYJb1iEfiHC7Y+VvmP/tviQyA5IR32mwN/5hTEJx6Ng==" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js"></script>
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% block javascript %}
    {% endblock %}
  </body>
  <style type="text/css">
    body{
      margin: 0;
      padding: 0;
    }
  </style>
</html>

to_anime/templates/to_anime/photo_list.html
{% extends 'to_anime/index.html' %}

{% block javascript %}
<script>
	$(function () {

		/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
		$("#id_file").change(function () {
			if (this.files && this.files[0]) {
				var reader = new FileReader();
				reader.onload = function (e) {
					$("#image").attr("src", e.target.result);
					$("#modalCrop").modal("show");
				}
				reader.readAsDataURL(this.files[0]);
			}
		});

		/* SCRIPTS TO HANDLE THE CROPPER BOX */
		var $image = $("#image");
		var cropBoxData = {
			width: 256,
			height: 256
		};
		var canvasData;
		$("#modalCrop").on("shown.bs.modal", function () {
			$image.cropper({
				strict: true,
        cropBoxResizable:false,
        autoCropArea: 0,
        resize:false,
        strict: false,
       
        highlight: false,
        dragCrop: false,
        zoomable: false,
        zoomOnTouch: false,
        zoomOnWheel: false,
        // viewMode: 3,
       
        dragMode: 3,
				ready: function () {
					$image.cropper("setCanvasData", canvasData);
					$image.cropper("setCropBoxData", { width: 256, height: 256 });
				}
			});
		}).on("hidden.bs.modal", function () {
			cropBoxData = $image.cropper("getCropBoxData");
			canvasData = $image.cropper("getCanvasData");
			$image.cropper("destroy");
		});

// Enable zoom in button
$(".js-zoom-in").click(function () {
	$image.cropper("zoom", 0.1);
});

// Enable zoom out button
$(".js-zoom-out").click(function () {
	$image.cropper("zoom", -0.1);
});
			// ...

			/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
			$(".js-crop-and-upload").click(function () {
				var cropData = $image.cropper("getData");
				$("#id_x").val(cropData["x"]);
				$("#id_y").val(cropData["y"]);
				$("#id_height").val(256);
				$("#id_width").val(256);
				$("#formUpload").submit();
			});

		});
	</script>
	{% endblock %}

	{% block content %}
	<div class="container">
		<div class="row">
			<h2 class="text-center">Selfie to Anime</h2>
			<img src="{{ MEDIA_URL }}result_train.png" class="thumbnail" style="margin-left: 400px">
		</div>


		<!-- FORM TO UPLOAD THE IMAGES -->
		<form method="post" enctype="multipart/form-data" id="formUpload">
			{% csrf_token %}
			{{ form }}
		</form>

		<!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
		{% if anime %}	
			<div class="row" style="margin-left: 160px">
				<div class="col-md-6">
					<img src="{{ MEDIA_URL }}{{original}}" class="img-thumbnail">
				</div>
				<div class="col-md-6">
					<img src="{{ anime.file.url }}" class="img-thumbnail">
				</div>
			</div>
		{% endif %}
	</div>
	

	<!-- MODAL TO CROP THE IMAGE -->
	<div class="modal fade" id="modalCrop">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">Crop the photo</h4>
				</div>
				<div class="modal-body">
					<img src="" id="image" style="max-width: 100%;">
				</div>
				<div class="modal-footer">
					<div class="btn-group pull-left" role="group">
						<button type="button" class="btn btn-default js-zoom-in">
							<span class="glyphicon glyphicon-zoom-in"></span>
						</button>
						<button type="button" class="btn btn-default js-zoom-out">
							<span class="glyphicon glyphicon-zoom-out"></span>
						</button>
					</div>
					<button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
					<button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
				</div>
			</div>
		</div>
	</div>
	
	
	
	{% endblock %}